// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/login" | "/register";
  };
  "./pages/home.tsx": {
    id: "pages/home";
    page: "/";
  };
  "./pages/about.tsx": {
    id: "pages/about";
    page: "/about";
  };
  "./pages/auth/login.tsx": {
    id: "pages/auth/login";
    page: "/login";
  };
  "./pages/auth/register.tsx": {
    id: "pages/auth/register";
    page: "/register";
  };
};